### ISSUE TITLE
Repository migration

### ISSUE THREAD

**Issue by TakayukiHoshi1984** [DeviceConnect/DeviceConnect#20]
プラットフォームごとにレポジトリを分割・移行しました。
更新がある場合は、移行先のレポジトリに行われます。
移行先のレポジトリは以下の通りです。

DeviceConnect-Docs
https://github.com/DeviceConnect/DeviceConnect-Docs

DeviceConnect-Android
https://github.com/DeviceConnect/DeviceConnect-Android

DeviceConnect-JS
https://github.com/DeviceConnect/DeviceConnect-JS

DeviceConnect-iOS
https://github.com/DeviceConnect/DeviceConnect-iOS

DeviceConnect-Common
https://github.com/DeviceConnect/DeviceConnect-Common

**Comment by yamazoet** [comment]
・https://github.com/DeviceConnect/DeviceConnectのReadmeでの移行の案内
・各レポジトリの英語でのReadmeの修正
